### PR TITLE
Add support for printing Realtek Ethernet switch tags to print-realtek.c

### PR DESCRIPTION
**Pull request by luizluca**

### CODE REVIEW

**Comment by guyharris** [comment]
So do *all* packets begin with a 6-octet destination address, a 6-octet source address, and a 2-octet Ethernet type of 0x8899?

And can you ever get a mixture of those packets and regular Ethernet packets when capturing?

**Comment by luizluca** [comment]
> So do _all_ packets begin with a 6-octet destination address, a 6-octet source address, and a 2-octet Ethernet type of 0x8899?

AFAIK, yes. I couldn't capture any frame that does not follow that sequence. I even wrote a [wireshark dissector](https://github.com/luizluca/wireshark-dissectors) (lua):

image

> And can you ever get a mixture of those packets and regular Ethernet packets when capturing?

It is not expected. I guess the switch would drop a packet from the CPU port without the proprietary tag. It would not know how to forward it. If it was the CPU (linux) that received it, the current driver will warn and possibly drop it.

**Comment by infrastation** [comment]
Please note that the packet diagrams, as they are now, display all fields 1 octet long (including MAC addresses and EtherType). To fix this, please look at the size ruler on the left side of the existing Marvell DSA packet diagram. Also it would be better to spell "Realktek" properly.

**Comment by luizluca** [comment]
> Please note that the packet diagrams, as they are now, display all fields 1 octet long (including MAC addresses and EtherType). To fix this, please look at the size ruler on the left side of the existing Marvell DSA packet diagram. Also it would be better to spell "Realktek" properly.

Oh, I see. The +6, +1... I'll add them. Thanks

**Comment by infrastation** [comment]
https://en.wikipedia.org/wiki/Realtek_Remote_Control_Protocol seems to be appropriate. It is possible to format packet diagrams nicely in Mediawiki ([example](https://en.wikipedia.org/wiki/IPv4#Header)), although I do not remember ever trying that. In the most basic case a PRE block with ASCII art would be better than nothing, I guess.

**Comment by luizluca** [comment]
OK. Wikipedia it is. Thanks. Closing this PR

**Comment by luizluca** [comment]
Draft submitted:

https://en.wikipedia.org/wiki/Draft:Realtek_Layer_2_Protocols

**Comment by guyharris** [comment]
See print-realtek.c in the main branch; I took print-rrcp.c and modified it to handle protocols other than RRCP, and added references to some Realtek documents describing RRCP, RLDP, and REP packets, as well as something that might describe one form of Realtek tag.

If this doesn't make it into the Wikipedia (which it might not), then:

- if there are Realtek documents available that describe the tag formats, please update print-realtek.c to handle those tag formats and point to the documents in question, mentioning where in the document the tag format is described;
- if there *aren't* Realtek documents available that describe the tag formats, please update print-realtek.c to handle those tag formats and document them in the code, noting that they were determined by reverse engineering or however they were determined.

**Comment by guyharris** [comment]
I'm reopening this for adding tag support to print-realtek.c.  (I'd do it myself but I don't have files with which to test it.)

**Comment by guyharris** [comment]
Never mind, that's for tcpdump, not for tcpdump-htdocs.

**Pull request closed without merging**
