### PR TITLE
Rename the DSA tag linktype pages

### PR DESCRIPTION
**Pull request by vivien**
This PR simply renames the Broadcom page describing the `LINKTYPE_DSA_TAG_BRCM*` macros and the Marvell DSA tag page describing the `LINKTYPE_DSA_TAG_*DSA` macros, so that their URLs are consistent with the other link types described at https://www.tcpdump.org/linktypes/.
Cc: @ffainelli

### CODE REVIEW

**Comment by vivien** [comment]
@guyharris any chance you pick this up?

**Comment by guyharris** [comment]
> This PR simply renames the Broadcom and Marvell DSA tag pages according to their LINKTYPE_* macros

There are four such LINKTYPE_ values and two such pages, so it's not exactly doing that; the broadcom-switch-tag.html page is used both for `LINKTYPE_DSA_TAG_BRCM` and `LINKTYPE_DSA_TAG_BRCM_PREPEND` and the marvell-switch-tag.html page is used both for `LINKTYPE_DSA_TAG_DSA` and `LINKTYPE_DSA_TAG_EDSA`.

**Comment by vivien** [comment]
I'm not sure to understand what you want me to do. I've reworded the Pull Request description if that is what you were concerned about.

**Comment by guyharris** [comment]
> I'm not sure to understand what you want me to do.

Think about whether this change is the right thing to do.  There's no *requirement* that a given page describe one and only one LINKTYPE_ value, and thus there's no *requirement* that a given page's name be the name of a LINKTYPE_ value with `.html` appended.

**Comment by vivien** [comment]
So you ignored this PR because you expected me to _think_ about my change? Well, I did. Here's my thought: someone browses https://www.tcpdump.org/linktypes/ and notices that 30+ pages under this *linktypes* resource URL are named after macros defined by libpcap, except for two pages: _broadcom-switch-tag.html_ and _marvell-switch-tag.html_.

So I renamed `broadcom-switch-tag.html -> LINKTYPE_DSA_TAG_BRCM.html` to match the described `LINKTYPE_DSA_TAG_BRCM` and `LINKTYPE_DSA_TAG_BRCM_PREPEND` macros and renamed `marvell-switch-tag.html -> LINKTYPE_DSA_TAG_DSA.html` to match the described `LINKTYPE_DSA_TAG_DSA` and `LINKTYPE_DSA_TAG_EDSA` macros.

This makes consistent and predictable resource URLs for documentation, which is always appreciated. I thought you would share this view, having an hardcoded *requirement* or not.

I also thought about adding `LINKTYPE_DSA_TAG_BRCM_PREPEND.html -> LINKTYPE_DSA_TAG_BRCM.html` and `LINKTYPE_DSA_TAG_EDSA.html -> LINKTYPE_DSA_TAG_DSA.html` symlinks to push consistency even further, but I wanted to have your opinion first. Almost 4 months later, here we are.

**Comment by mcr** [comment]
@guyharris, We could put hard links in when we have an TAG:PAGE that is not 1:1.  So this rename seems reasonable to me.

**Comment by infrastation** [comment]
Hard links do not exist as far as git is concerned.

**Comment by mcr** [comment]
Denis Ovsienko <notifications@github.com> wrote:
    > Hard links do not exist as far as git is concerned.

symlinks do, and would work fine.

**Comment by infrastation** [comment]
As a single specification file defines one or more link types, to me the most sense would make the following instead of the originally proposed renaming:
```text
something.html
LINKTYPE_SOMETHING1.html -> something.html
LINKTYPE_SOMETHING2.html -> something.html
LINKTYPE_SOMETHING3.html -> `something.html
something_else.html
LINKTYPE_SOMETHINGELSE1.html -> something_else.html
LINKTYPE_SOMETHINGELSE2.html -> something_else.html
```

**Comment by infrastation** [comment]
Thank you for stating the problem and proposing a solution. Commit 9cca92c solves it in a different way so all HTML files listed at https://www.tcpdump.org/linktypes/ now follow the convention. Closing.

**Pull request closed without merging**
