### PR TITLE
Add LINKTYPE_FLEXRAY

### PR DESCRIPTION
**Pull request by kayoub5**
# Context
* The LINKTYPE_FLEXRAY is already allocated in libpcap (see https://github.com/the-tcpdump-group/libpcap/blob/bcca74d2713dc9c0a27992102c469f77bdd8dd1f/pcap-common.c#L606)
* The link type was not documented in the website
* I found a specification in https://gitlab.com/wireshark/wireshark/-/issues/12033 (WireShark already support the link type FlexRay)
* I took the word document and converted it to HTML so it's available for everyone.

CC @LarsVoelker

### CODE REVIEW

**Comment by infrastation** [comment]
Please make the new page appear in `htmlsrc/linktypes` (without duplicate copies of the header and the footer) so `regen_html_pages.sh` can pick it up and produce the file in `linktypes`. Likewise, please modify `htmlsrc/linktypes.html` instead of `linktypes.html`.

**Comment by kayoub5** [comment]
@infrastation done

**Comment by infrastation** [comment]
Thank you. In the proposed changes did you mean `DLT_FLEXRAY` instead of `DLT_IPMB_LINUX`?

**Comment by kayoub5** [comment]
@infrastation yes

**Comment by kayoub5** [comment]
@infrastation PR ready.

**Comment by infrastation** [comment]
Thank you. I have squashed these commits and rebased on the current master branch. Please mind that www.flexray.com is no longer a relevant web-site, also the HTML version has lost the "FlexRay Frame Data Packet" header altogether and the notion of size range in a few other headers. Would you like to put that right before merging?

**Comment by kayoub5** [comment]
@infrastation link and headers fixed, ready to merge.

**Comment by infrastation** [comment]
Thank you.

**Comment by guyharris** [comment]
Do you know whether that matches what Hannes Kaelber intended when he asked for LINKTYPE_FLEXRAY/DLT_FLEXRAY?

**Comment by kayoub5** [comment]
@guyharris No, Hannes Kaelber used the `DLT_FLEXRAY` for a limited scenario and approved the change of the layout when he was contacted about it.

The new layout is being actively used, and is supported by Wireshark.

See https://lists.sandelman.ca/pipermail/tcpdump-workers/2016-January/000476.html
```
> 2016-01-15 21:35 GMT+01:00 Guy Harris <guy at alum.mit.edu>:
>
> On Jan 15, 2016, at 10:44 AM, Guenter Ebermann <guenter.ebermann at googlemail.com> wrote:
>
> I don't know whether Hannes still works at X2E.  You might want to try sending an e-mail to him asking whether a format for DLT_FLEXRAY was ever defined - and, if it has, asking him to send me a copy so that I can add it to the link-layer header types page:
>
>         http://www.tcpdump.org/linktypes.html
>
> (and, if any of the *others* were defined, to send those to me as well).
>
> If mail to him bounces, you could try contacting X2E to see if that information is available, or if they ever supporting writing out files in pcap or pcapng format.
>
> If they never wrote files out with a link-layer header type of 210 for DLT_FLEXRAY/LINKTYPE_FLEXRAY, then you can use it for your own purposes - send us the spec and I'll add it to the link-layer header types page.
>
> If they did, but they don't tell you what format they use, we can create a new LINKTYPE_/DLT_ value for your format, and provide a public specification for that one.

I asked Hannes about DLT_FLEXRAY.
He told me that they currently dont use pcap for FlexRay and have only
used it in a limited scenario and that we are free to change the
layout.
The format represented the bitsream from the bus 1:1 without an
additional header.
The only deviation was the padding: the data was padded to align to 4
byte boundaries.

This is my suggestion for an extension:

I want to extend the frame by a "measurement-header": This header is
added by the measurement device. It contains one bit for the FlexRay
channel (A or B), a "data-type" enumeration and error-flags.

Error-flags will be all kind of decoding errors which may be detected
during capture of a FlexRay frame. That is: TSS, FSS, BSS, or FES
violations. Header CRC or Frame CRC errors and all kind of
"short-item-counts" that is, if not all bytes of the frame-bitstream
could be captured.

One enum-value of the "data-type" will be for a "data-frame", whereas
a data frame would have exactly the same coding as on the FlexRay bus.

The second enum-value of the "data-type" will be a "flexray-symbol",
which contains the bitlength information of the captured FlexRay
symbol (used for CAS and Wakeup).

BR
Günter
```

**Pull request merged**
